# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, development]
  pull_request:
    branches: [main, master, development]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java -version

      - name: Install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev

      - name: R CMD javareconf (unix)
        run: |
          sudo R CMD javareconf

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage
          working-directory: mallet

      - name: Test coverage
        run: covr::codecov(path ="mallet", token = Sys.getenv("CODECOV_TOKEN"), quiet = FALSE)
        shell: Rscript {0}


